In [2]:
import numpy as np
a=np.array([[[0.4,0.2],[0.3,0.2]],
[[0.9,0.2],[0.2,0.2]],
[[0.3,0.2],[0.5,0.2]]])


In [4]:
a[:,::-1,:]
a[0,1,1]

0.2

In [156]:
out_j=a
import scipy.special


In [157]:
b=out_j[:-1, :, :]
b

array([[[0.4, 0.2],
        [0.3, 0.2]],

       [[0.9, 0.2],
        [0.2, 0.2]]])

In [158]:
prob = scipy.special.softmax(out_j[:-1, :, :], axis=0)

prob

array([[[0.37754, 0.5    ],
        [0.52498, 0.5    ]],

       [[0.62246, 0.5    ],
        [0.47502, 0.5    ]]])

In [162]:
prob = [[[1,2,23],
[8,9,56]],
[[2,4,2],
[4,6,57]],
[[5,8,2],
[4,6,57]]]
testt = np.argmax(prob, axis=0)
print("testt",testt)
loc1 = np.sum(prob, axis=0)
print("loc1",loc1)
loc1 = np.sum(prob, axis=1)
print("loc1 2",loc1)
idx = np.arange(2) + 1
idx = idx.reshape(-1, 1, 1)
print("prob * idx",prob * idx)
loc = np.sum(prob * idx, axis=0)
print()

out_j = np.argmax(out_j, axis=0)
loc[out_j == 1] = 0
loc

testt [[2 2 0]
 [0 0 1]]
loc1 [[  8  14  27]
 [ 16  21 170]]
loc1 2 [[ 9 11 79]
 [ 6 10 59]
 [ 9 14 59]]


ValueError: operands could not be broadcast together with shapes (3,2,3) (2,1,1) 

In [131]:

out_j

0

In [132]:
col_sample = np.linspace(0, 800 - 1, 200)
col_sample_w = col_sample[1] - col_sample[0]
print(col_sample_w)
cls_num_per_lane = 18
row_anchor = [121, 131, 141, 150, 160, 170, 180, 189, 199, 209, 219, 228, 238, 248, 258, 267, 277, 287]

for i in range(out_j.shape[1]):
    if np.sum(out_j[:, i] != 0) > 2:
        for k in range(out_j.shape[0]):
            if out_j[k, i] > 0:
                ppp = (int(out_j[k, i] * col_sample_w* 1640/ 800) - 1, int(459 * (row_anchor[cls_num_per_lane-1-k]/288)) - 1 )
                print("write circle",ppp)

4.015075376884422


IndexError: tuple index out of range

In [185]:
test = [[1,2],[1,2]]
test1 = [[1,2],[1,2]]
test1[test==2]=0
test1

[0, [1, 2]]

In [167]:
test==0

False